export const DETAILS = {
  EXPECTED_STRING: "EXPECTED_STRING",
  INVALID_EMAIL: "INVALID_EMAIL",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  REQUIRED: "REQUIRED",
};
